ambassador:
    image: cpuguy83/docker-grand-ambassador
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-name laravelrealtime_nginx_1 -name laravelrealtime_php_1 "
redis:
    image: tutum/redis
    expose:
        - 6379:6379
    environment:
        REDIS_PASS: "**None**"
        REDIS_APPENDONLY: "yes"
        REDIS_APPENDFSYNC: everysec
application:
    build: ./code
    volumes:
        - ./code/laravel:/var/www/laravel
        - ./logs/laravel:/var/www/laravel/storage/logs
    tty: true
db:
    image: mysql
    expose:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
php:
    build: ./php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
        - redis
        - ambassador:nginx
artisan:
    build: ./artisan
queuelisten:
    build: ./artisan
    volumes_from:
        - application
    links:
        - db
        - redis
        - ambassador:nginx
    command: "queue:listen"
queueworker:
    build: ./artisan
    volumes_from:
        - application
    links:
        - db
        - redis
        - ambassador:nginx
    command: "queue:work connection --daemon --tries=3"
nginx:
    build: ./nginx
    ports:
        - 80:80
    links:
        - ambassador:php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx
elk:
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - ./elk/logstash:/etc/logstash
        - ./elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - application
        - php
        - nginx
